### ISSUE TITLE
App.ActiveDocument in onchanged

### ISSUE THREAD

**Issue by DeepSOIC** [iplayfast/CycloidGearBox#1]
https://github.com/iplayfast/CycloidGearBox/blob/a7151ecb65d268f9bb9a7a0c3fd097a633969774/cycloidbox.py#L176

Don't. `App.ActiveDocument` is what doc is on user's screen, not what doc the "pinDisk" object is. Use `fp.Document` instead

**Comment by iplayfast** [comment]
I've added your suggestion to the onChanged functions. Thanks for the input, let me know if there are other places it should also be.
