### ISSUE TITLE
Workbench fails to load on Windows

### ISSUE THREAD

**Issue by dkulinski** [iplayfast/CycloidGearBox#5]
The workbench fails to load on Windows this this error in the console:

During initialization the error "cannot import name 'YESEXPR' from 'locale' (C:\Program Files\FreeCAD 0.20\bin\lib\locale.py)" occurred in C:\Users\danie\AppData\Roaming\FreeCAD\Mod\CycloidGearBox\InitGui.py

FreeCAD Weekly build [FreeCAD_0.20.27422_Win-LPv12.5.4_vc19-x86-64.exe](https://github.com/FreeCAD/FreeCAD-Bundle/releases/download/weekly-builds/FreeCAD_0.20.27422_Win-LPv12.5.4_vc19-x86-64.exe)

A quick google shows this to be a platform specific issue in Python.

**Comment by RobotToaster** [comment]
I guess this is why it's not loading for me.

**Comment by iplayfast** [comment]
I think you might want to give this issue to the freecad project https://github.com/FreeCAD/FreeCAD. I'm just and addon to it.
