### ISSUE TITLE
Crash because out of RAM

### ISSUE THREAD

**Issue by schnili** [iplayfast/CycloidGearBox#6]
I wanted to try this out but it crashes after printing 
```
CycloidalGearBox.Activated()
gearbox created
doc.recompute started
cyloidFun creating parts
pindisk
driverdisk
inputShaft
cycloidal Disk 1
cycloidal Disk 2
eccentric Key
outputShaft
cyloidFun creating parts
```
as FreeCAD starts to consume more than 16gb memory.

I just downloaded a new weekly build AppImage from GitHub
[FreeCAD_weekly-builds-28929-2022-05-26-conda-Linux-x86_64-py39.AppImage](https://github.com/FreeCAD/FreeCAD-Bundle/releases/download/weekly-builds/FreeCAD_weekly-builds-28929-2022-05-26-conda-Linux-x86_64-py39.AppImage)

Anyways, thanks for writing this :)

**Comment by iplayfast** [comment]
It's been updated since May  so some memory issues might have been fixed. Also try reducing the number of linesegments. The gears won't be as smooth but might still be ok.
